server:
  port: 19000
  servlet:
    context-path: /mcp-client
    # 强制设置编码为 UTF-8
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

spring:
  application:
    name: mcp-client
  data:
    redis:
      host: 127.0.0.1
      port: 9379
      password: 123456

logging:
  level:
    root: info
    org.willingoxjin: debug

# Spring AI Config
---
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL} # 调用api地址
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL} # 模型:deepseek-chat
    # 向量配置
    vectorstore:
      redis:
        initialize-schema: true             # 是否初始化所需模式
        index-name: rag-vector              # 用于向量存储的索引名
        prefix: 'rag_document:'             # 存储到 Redis key 前缀